builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
      - "386"

archives:
  - id: archives
    format: binary
    name_template: "{{ .ProjectName }}-{{ .Os }}-{{ .Arch }}"

checksum:
  name_template: "{{ .ProjectName }}-checksums.txt"

snapshot:
  name_template: "git-{{.Commit}}"

release:
  name_template: "v{{.Version}}"

changelog:
  skip: true

brews:
  - name: fuzzy-clone
    repository:
      owner: kjuulh
      name: homebrew-fuzzy-clone
      token: "{{.Env.TAP_GITHUB_TOKEN}}"

    download_strategy: CurlDownloadStrategy

    commit_author:
      name: goreleaserbot
      email: bot@goreleaser.com

    commit_msg_template: "Brew formula update for {{ .ProjectName }} version {{ .Tag }}"

    folder: Formula

    caveats: |
      Run either fuzzy-clone directory or

      # zsh
      echo 'eval "$(fuzzy-clone init zsh)"' >> ~/.zshrc

    homepage: "https://kasperhermansen.com"

    description: "Fuzzy clone is a fuzzy repository picker and downloader, it allows you to quickly jump between repositories you contribute to, whether you have them downloaded or not."

    license: "MIT"

    # So you can `brew test` your formula.
    #
    # Template: allowed
    test: |
      system "#{bin} --version"
